
const profileRoute=require('./routes/profileRoute');
const requestRoute=require('./routes/requestRoute');
const postRoute=require('./routes/postRoute');
const chatRoute=require('./routes/chatRoute');
const authRoute=require('./routes/authRoute');
const mongoose=require('mongoose');
const express=require('express');
const User=require('./models/userSchema');
mongoose.set('useNewUrlParser', true);
mongoose.set('useUnifiedTopology', true);
mongoose.set('useCreateIndex', false);
mongoose.set('useFindAndModify',false);
mongoose.connect('mongodb://localhost:27017/userDetails');
const app=express();
app.use(express.json());
app.use(authRoute);
app.use(profileRoute);
app.use('/request',requestRoute);
app.use('/mypost',postRoute);
app.use(chatRoute);
app.listen(3000);
