const mongoose=require('mongoose');
const shortid=require('shortid');
const UserSchema=mongoose.Schema(
    {
        userId:{
            type:String,
            default:shortid.generate
        },
        firstName:{
            type:String,
            required:true           
        },
        lastName:{
            type:String,
            required:true
        },
        emailId:{
            type:String,
            required:true
        },
        phnNo:{
            type:Number,
            required:true
        },
        password:{
            type:String,
            required:true,
        },
        userName:{
            type:String,
            required:true,
        },
        
        post:[
            {
                postId:{
                    type:String,
                   
                },
                postType:{
                    type:String,
                    default:"None"
                },
                postContent:{
                    type:String,
                    default:"None"
                },
                postedOn:{
                    type:Date,
                    default:Date.now
                },
               
            }
        ],
        comment:[ 
            {
                postId:{
                    type:String
                },
                commentedBy:{
                    type:String
                },
                comment_text:{
                    type:String,
                    default:"Nice post"
                },
                commentedOn:{
                    type:Date,
                    default:Date.now
                }
            } 
        ],
        likes:[
             {
                 postId:{
                     type:String
                 },
                likedBy:{
                    type:String
                },
                likedOn:{
                    type:String
                } 
            }
            ],
        friends:[
            {
                friendId:{
                    type:String,
                    default:"None"
                },
                ConnectedOn:{
                    type:Date,
                    default:Date.now
                }
            }
        ],
        friend_request:[
            {
                senderId:{
                    type:String,
                    default:"None"
                },
                senderName:{
                    type:String,
                    default:"None"
                },
                requestedOn:{
                    type:Date,
                    default:Date.now
                }
            }
        ],
        profile:
            {
            profilePic:
            {
                type:String,
                default:"https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.shutterstock.com%2Fsearch%2Fuser%2Bprofile&psig=AOvVaw1lif9IMQhqA4HMUn9eAjt9&ust=1598622091864000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCIimh8TBu-sCFQAAAAAdAAAAABAD"
            },
            dob:{
                type:Date,
                default:Date.now
            },
            relationship_status:
            {
                type:String,
                default:"Single"
            },
            location:{
                type:String,
                default:"None"
            },        
            workplace:
            {
                type:String,
                default:"None"
            },
            school_college:
            {
                type:String,
                default:"None"
            }
                }
                 
    });
var userDetails=mongoose.model("user",UserSchema);
module.exports=userDetails;